<?php

/**
 * @file
 * navigation menu module
 *
 *
*/


/**
 * Implementation of hook_menu()
*/

function ixodes_scapularis_menu() {
  $items['organism/ixodes_scapularis'] = array(
    'title' => 'Ixodes scapularis',
    //'title callback' => 'navigation_title',
    'page callback' => 'ixodes_scapularis',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => 3,
  );
  return $items;
}

function ixodes_scapularis( $section = '' ){
  return t('Ixodes scapularis... section: @section', array('@section' => $section));
}


