<?php
/**
 * @file
 * Displays a block with xcel (such as anoxcel) data.
 * author: Andrew Sheehan
 *
 */
 
/**
 * implementation of hook_block_info
 * @return array $blocks
 */
function xcel_block_info() {
  $blocks['xcel_block'] = array(
    'info' => t('XCel Block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function xcel_block_configure($delta='') {
  $form = array();
 
  switch($delta) {
    case 'xcel_block' :
      // Text field form element
      $form['text_body'] = array(
        '#type' => 'text_format',
        '#title' => t('Enter your text here in WYSIWYG format'),
        '#default_value' => variable_get('text_variable', ''),
      );
 
      // File selection form element
      $form['file'] = array(
        '#name' => 'block_image',
        '#type' => 'managed_file',
        '#title' => t('Choose an Image File'),
        '#description' => t('Select an Image for the custom block.  Only *.gif, *.png, *.jpg, and *.jpeg images allowed.'),
        '#default_value' => variable_get('block_image_fid', ''),
        '#upload_location' => 'public://block_image/',
        '#upload_validators' => array(
          'file_validate_extensions' => array('gif png jpg jpeg'),
        ),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_view().
 */
function xcel_block_view($delta='') {
  $block = array();
 
  switch($delta) {
    case 'xcel_block' :
      $block['content'] = anoxcel_block_view();
      break;
  }
 
  return $block;
}

function xcel_plainText($text) {
	drupal_set_header('Content-Type: text/plain');
	print $text;
	exit(0);
}
 
/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function anoxcel_block_view() {
  $block = array();
 
  $protein = $_GET["protein"];
  $displayResults = "";
  $outputFile = "";
  $outputFileLocation = "/vectorbase/web/vbpre/data/BAC_files/$protein";

  $result = db_query("SELECT * FROM anoxcel WHERE \"Protein\" = :protein", array(":protein" => $protein));
  foreach ($result as $resultObject){
    foreach ($resultObject as $key => $value) {
      $displayResults .= "<tr><td>" . $key . "</td><td>" . $value. "</td></tr>";
      $outputFile .= "$key\t$value\n";
    }
  }

  //xcel_plainText($outputFile);
  file_put_contents($outputFileLocation, $outputFile);
 

  // Block output in HTML with div wrapper
  $block = array(
    'label' => array(
      '#prefix' => '<h3>',
      '#type' => 'markup',
      '#markup' => $protein,
      '#suffix' => '</h3>',
    ),/*
    'content' => array(
      '#prefix' => '<a href=',
      '#type' => 'markup',
      '#markup' => $outputFileLocation,
      '#suffix' => '>Download as file</a>',
    ),*/
    'result' => array(
      '#prefix' => '<table>',
      '#type' => 'markup',
      '#markup' => $displayResults,
      '#suffix' => '</table>',
    ),
  );
 
  return $block;
}
