<?php

/**
 * @file
 * navigation menu module
 *
 *
*/


/**
 * Implementation of hook_menu()
*/

function anopheles_gambiae_menu() {
  $items['organism/aedes_aegypti'] = array(
    'title' => 'Anopheles gambiae',
    //'title callback' => 'navigation_title',
    'page callback' => 'anopheles_gambiae',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => 1,
  );
  return $items;
}

function anopheles_gambiae( $section = '' ){
  $ret = "<iframe src=http://www.vectorbase.org/Anopheles_gambiae/Info/Index width=700 height=800></iframe>";
  return $ret;
  //return t('Anopheles gambiae... section: @section', array('@section' => $section));
}


