<?php

/**
* @file
* Legal Agreement for VectorBase user registration.
*
*/

/**
* Implements hook_form_alter().
*/
function legalagree_form_alter(&$form, &$form_state, $form_id) {

	if(!($form_id == 'user_register_form' || $form_id == 'user_profile_form')) {
		return;
	}
	$form['#validate'][] = 'legalagree_user_form_validate';
	$form['account']['legal_agreement'] = array(
		'#type' => 'fieldset',
		'#title' => t('Legal Agreement (Not the Usual Yadda Yadda)'));


	$form['account']['legal_agreement']['decision'] = array(
		'#type' => 'radios',
		'#description' => t('By registering as a user of %site-name, you agree to be excellent to each other, and always carry a towel.',
			array('%site-name' => variable_get('site_name', 'drupal'))),
		'#default_value' => 0,
		'#options' => array(t('Bogus!'), t('Party on, dudes!')));
}

/*
* Form validation handler for current password on user_account_form()
*
* @see user_agreement_form()
*/
function legalagree_user_form_validate($form, &$form_state) {
	global $user;
	if($form_state['input']['decision'] <> 1) {
		form_set_error('decision', t('Bummmer, dude, we can\'t let you register without agreeing to the legal agreement first.'));
	} else {
		watchdog('user', t('User %user agreed to legal terms', array('%user' => $user->name)));
	}
}
