<?php

// $Id:

/**
 * @file
 * Fast Gallery allows you to build galleries based on your file
 * system with folders and subfolders.
 *
 * This file is mainly used connecting the fast gallery module with drupal
 * it though contains hardly any logic. This is being directed to either the
 * Fast Gallery controller (fast_gallery.class.php) or the storage engine
 *
 * This module is sponsored by Schär Webdesign.
 * Visit www.schaerwebdesign.ch or the Drupal-related blog www.rapsli.ch.
 *
 * Original version by Raphael Schär - www.schaerwebdesign.ch.
 *
 * @author Raphael Schär - www.schaerwebdesign.ch
 */

define('FG_DEFAULT_STORAGE_ENGINE','default');

/**
 * Implementation of hook_permission
 * @return array
 */
function fast_gallery_permission() {
  return array(
  'administer fast gallery' => array(
  'title' => t('Administer Fast Gallery'),
  'description' => t('Administer Fast Gallery settings'),
  ),
  );
}

function fast_gallery_help($path, $arg) {
  switch ($path) {
    case 'admin/config/fast_gallery':
      return t('You have the default options and the options that depend on the
      storage engine you have selected.');
      break;
  }
}


/**
 * Implementation of hook_menu
 * @return array
 */
function fast_gallery_menu() {
  $items['admin/config/fast_gallery'] = array(
      'title' => 'Fast Gallery',
      'description' => 'Configure the fast gallery module',
      'page callback' => 'system_admin_menu_block_page',
      'file' => 'system.admin.inc',
      'access arguments' => array('administer fast gallery'),
      'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/fast_gallery/general'] = array(
      'title' => 'General configuration',
      'description' => 'Configure the fast gallery module',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('fast_gallery_general_settings_form'),
      'access arguments' => array('administer fast gallery'),
      'file' => 'fast_gallery.admin.inc',
      'file path' => drupal_get_path('module', 'fast_gallery'),
  );

  $items['fast_gallery/ajax/%op'] = array(
      'page callback' => 'fast_gallery_ajax_handler',
      'page arguments' => array(2),
      'access arguments' => array('administer fast gallery'),
      'file' => 'fast_gallery.admin.inc',
      'file path' => drupal_get_path('module', 'fast_gallery'),
  );

  $fg_galleries = variable_get('fg_galleries', array());
  foreach ($fg_galleries as $gallery) {
    $items[$gallery['fg_alias']] = array(
        'page callback' => 'fast_gallery_page_alias',
        'page arguments' => array($gallery['fg_path']),
        'access arguments' => array('access content'),
        'title' => $gallery['fg_title'],
    );
  }

  $engine = variable_get('fg_storage_engine', array());
  if ($engine['config'] != '') {
    $items[$engine['config']] = array(
        'title' => $engine['name'] . ' - Storage engine',
        'page callback' => $engine['config_callback'],
        'access arguments' => array('administer fast gallery'),
        'file path' => $engine['path'],
        'file' => $engine['config_file'],
        'description' => 'Specific configuration options for this storage engine'
    );
  }

  $items['fast_gallery/clearcache'] = array(
    'title' => 'Clear Fast Gallery Cache',
    'type' => MENU_CALLBACK,
    'page callback' => 'fast_gallery_clear_cache',
    'access arguments' => array('edit iptc'),
  );
  //exit();
  return $items;
}

/**
 * implementation of hook_fast_gallery_info()
 * Let's Fast Gallery know that we are implementing a storage engine
 * The following structure is needed
 * array(
 'fg_version' => 2, the version of fast_gallery
 'storageengine' => array(
 'default' => array( //needs to be identical with the param key
 'key' => 'default', //just an identifier for this engine
 'name' => 'Default', //a human readable name
 'file' => 'default.storage.inc', //the file where the class is located
 'path' => drupal_get_path('module', 'fast_gallery') . '/storageengine', //the path where the file is located
 'config' => 'admin/config/fast_gallery/default', //the path where the config is going to be
 'config_callback' => 'fast_gallery_default_config', //callback for this path
 'config_file' => 'default.config.inc', //the file where this callback needs to be -> folder is same as path
 ),
 ),
 );
 * @return array
 */
function fast_gallery_fast_gallery_info() {
  return array(
    'fg_version' => 2,
    'storageengine' => array(
    'default' => array(
      'key' => 'default',
      'name' => 'Default',
      'file' => 'default.storage.inc',
      'path' => drupal_get_path('module', 'fast_gallery') . '/storageengine',
      'config' => 'admin/config/fast_gallery/default',
      'config_callback' => 'fast_gallery_default_config',
      'config_file' => 'default.config.inc',
      'supported_files' => array('jpg', 'jpeg', 'png', 'gif', 'bmp', 'pdf'),
      ),
      'node' => array(
        'key' => 'node',
        'name' => 'Node <not implemented!!!>',
        'file' => 'node.storage.inc',
        'path' => drupal_get_path('module', 'fast_gallery') . '/storageengine',
        'config' => 'admin/config/fast_gallery/node',
      ),
    ),
    'presentation' => array(
      'lightbox' => array(
        'key' => 'lightbox',
        'name' => 'Lightbox',
        'module' => 'fast_gallery',
        'file' => 'lightbox.presentation.inc',
        'path' => drupal_get_path('module', 'fast_gallery') . '/presentation',
      ),
    ),
  );
}

function _fast_gallery_get_alias_count($path) {
  $ar = explode("/", $path);
  if ($ar[count($ar)-1] == '') {
    array_shift($ar);
  }
  return count($ar);
}

/**
 * implementation of hook_block_info
 * @return array $blocks
 */
function fast_gallery_block_info() {
  $blocks['gallery_block'] = array(
    'info' => t('Fast Gallery Block'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * implementation of hook_block_view
 *
 * @param string $delta
 * @return array
 *  $block['subject']
 *  $block['content']
 */
function fast_gallery_block_view($delta) {
  $block = array();
  /*switch ($delta) {
    case 'random_image':
      $fg = fast_gallery_get_FastGallery();
      $block['subject'] = 'Fast Gallery';
      $block['content'] = $fg->getRandomImage()->renderHTML();
      break;
  }*/
  $gallery_default = variable_get('fg_galleries', array());
  //drupal_set_message(print_r($gallery_default));
  if (get_gallery_string(menu_get_object()) != '') {
    $block['content'] = fast_gallery_page_alias(NULL,'BLOCKMODE',4);
    return $block;
  }
}

/**
 * Callbackfunction when hitting a gallery page
 * @param $path
 * @return html string
 */
function fast_gallery_page_alias($path, $blockMode='NOT', $items=0) {
  //drupal_set_message(t($path));
  //drupal_set_message(t($items));
  //drupal_set_message(print_r(menu_get_object()));
  $current_path_alias = '';
  if ($blockMode == 'BLOCKMODE') {
    $menuObject = menu_get_object();
    //$galleryString = 'vbgallery/' . $menuObject->field_genus['und'][0]['value'] . ' Species/' . $menuObject->field_genus  ['und'][0]['value'] . ' ' . $menuObject->field_species['und'][0]['value'];
    $path = get_gallery_path($menuObject);
    $current_path_alias = get_gallery_string($menuObject);
  }
  $settings = variable_get('fg_galleries');

  if ($blockMode != 'BLOCKMODE') {
      $current_path_alias = check_plain($_GET['q']);
  }
  
  //drupal_set_message(t($current_path_alias));

  $start = strlen($settings[$path]['fg_alias']);
  $path_new = substr($current_path_alias, ++$start);
  $path_new  = $settings[$path]['fg_path'] . $path_new;

  //fetching the needed objects
  $fg = fast_gallery_get_FastGallery();
  $storage = $fg->getStorageEngine();

  drupal_set_breadcrumb($fg->buildBreadCrumbs());
  $current_path = check_plain($_GET['q']);

  $images = $storage->getImages($path_new);
  //drupal_set_message(t(print_r($images)));
  
  //if ((sizeof($images) < 1) && (preg_match('[.]...$',$path_new) > 0)) {
  //};
  
  $html = '';
  $imageCounter = 0;
  foreach ($images as $image) {
    if ($image->getName() != 'folder.png') {
    if ($image->isDir()) {//incase of a subfolder -> make a different link
      $image_html = l($image->renderHtml() . '<br>' . $image->getName(), $current_path . '/' . $image->getName(), array('html' => TRUE));
    } else {
      $imageCounter++;
      $imageDesc = $image->getDesc();
      $imageTitle = $image->getTitle();
      $imageCredit = $image->getCredit();
      $imageSource = $image->getSource();
      $titleBreak = '<br>';
      if ($imageDesc != '') {
        $imageText = str_replace(array("\r\n", "\n", "\r"),"<br>",$image->GetDesc());
      } else if ($imageTitle != '') {
        $imageText = $imageTitle;
      } else {
        $imageText = $image->getName();
      }
      if ($imageCredit != '') {
        $imageText = $imageText . "<br>" . $imageCredit;
      } else if ($imageSource != '') {
        $imageText = $imageText . "<br>";
      }
      if ($imageSource != '') {
        if (preg_match("/^PHIL:([0-9]+)$/", $imageSource, $matches)) {
          $philId = $matches[1];
          $imageText = $imageText . " (PHIL <a href='http://phil.cdc.gov/phil/details_linked.asp?pid=$philId' target='_BLANK'>$philId</a>)";
        } else {
          $imageText = $imageText . $imageSource;
        }
      }
      if (user_access('edit iptc')) {
        $editLink = ' <a href="/iptc_editor/edit?imagepath=' . $image->getPath() . '">(e)</a>';
      } else {
        $editLink = '';
      }
      if ($blockMode == 'BLOCKMODE') {
        $imageTitle = '';
        $editLink = '';
        $titleBreak = '';
      }
      $image_html = l($image->renderHtml() . $titleBreak . $imageTitle . $editLink, $image->getPath(), array('html' => TRUE, 'attributes' => array('rel' => 'lightbox[fast_gallery][' . $imageText . ']')));

    }

    //use .tpl file to output an image
    if (!(($image->isDir() || ($imageCounter > $items)) && $blockMode=='BLOCKMODE')) {
        $html .= theme('fast_gallery_image', array('image' => $image_html));
    }
  }
  }

  if ($html == '') {
    $html .= t('There are no images in this folder.');
  } else if ($blockMode == 'BLOCKMODE') {
    $html .= '<div style="width:300px;text-align:center;"><a href="/' . $current_path_alias . '">View Entire Gallery</a></div>';
  }
  return $html;
}

/**
 * Implementation of hook_cron() to keep gallery up-to-date.
 */
function fast_gallery_cron() {
  $fg = fast_gallery_get_FastGallery();
  $fg->rescanGallery();
}


/**
 * Implementation of hook_theme
 * @return array
 */
function fast_gallery_theme() {
  return array(
  'fast_gallery_image' => array(
  'variables' => array(
  'image' => NULL,
  'name' => NULL,
  ),
  'template' => 'fast_gallery-image',
  ),
  'fg_multiple_galleries' => array(
  'render element' => 'form',
  ),
  );
}

/**
 * Implementation of hook_flush_caches
 */
function fast_gallery_flush_caches() {
  db_truncate('cache_fast_gallery')->execute();
}

/**
 * Implementation of hook_init
 */
function fast_gallery_init() {
  drupal_add_css(drupal_get_path('module', 'fast_gallery') . '/fast_gallery.css');
}


/**
 * helper function to return the controller class
 * FastGallery
 * @return FastGallery
 */
function fast_gallery_get_FastGallery() {
  include_once('fast_gallery.class.php');
  return FastGallery :: getInstance();
}

/**
 * helper function to return the Cache
 * @return FastGalleryCache
 */
function fast_gallery_get_cache() {
  include_once('fast_gallery.cache.class.php');
  return FastGalleryCache::getInstance();
}

/**
 * helper function to clear the Cache after IPTC updates
 * @ return void
 */
function fast_gallery_clear_cache() {
  cache_clear_all('*', 'cache_fast_gallery', TRUE);
}

function get_gallery_string($menuObject) {
  $galleryString = '';
  if (property_exists($menuObject,'field_gallery_path')) {
    if (array_key_exists('und',$menuObject->field_gallery_path)) {
      $pathArray = $menuObject->field_gallery_path['und'];
      if (sizeof($pathArray) > 0) {
        $pathArray = $pathArray[0];
        if (array_key_exists('value',$pathArray)) {
          $galleryString = $pathArray['value'];
        }
      }
    }
  }
  return $galleryString;
}

function get_gallery_path($menuObject) {
  $galleryPath = '';
  if (property_exists($menuObject,'field_gallery_name')) {
    if (array_key_exists('und',$menuObject->field_gallery_name)) {
      $pathArray = $menuObject->field_gallery_name['und'];
      if (sizeof($pathArray) > 0) {
        $pathArray = $pathArray[0];
        if (array_key_exists('value',$pathArray)) {
          $galleryPath = $pathArray['value'];
        }
      }
    }
  }
  return $galleryPath;
}
