<?php

function test_menu(){
  $items['test'] = array(
      'title' => 'Test Stuff',
      'access arguments' => TRUE,
      'page callback' => 'test_overview',
      'type' => MENU_NORMAL_ITEM,
      );
  $items['test/list'] = array(
      'title' => 'Test List',
      'access arguments' => array('list'),
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'weight' => 0,
      );
  $items['test/add'] = array(
      'title' => 'Test Add',
      'access arguments' => array('add'),
      'page callback' => 'test_add',
      'type' => MENU_LOCAL_TASK,
      'weight' => 1,
      );
  return $items;
}

function test_overview() {
  $output = t('this is a tessssstttt....');
  return $output;
}

function test_add() {
  return t('test add plox');
}
