<?php

/**
 * @file
 * navigation menu module
 *
 *
*/


/**
 * Implementation of hook_menu()
*/

function aedes_aegypti_menu() {
  $items['organism/aedes_aegypti'] = array(
    'title' => 'Aedes aegypti',
    //'title callback' => 'navigation_title',
    'page callback' => 'aedes_aegypti',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => 6,
  );
  return $items;
}

function aedes_aegypti( $section = '' ){
  return t('Aedes... section: @section', array('@section' => $section));
}


