<?php

/**
 * @file
 * navigation menu module
 *
 *
*/


/**
 * Implementation of hook_menu()
*/

function tool_menu() {
  $items['tool'] = array(
    'title' => 'Tools',
    'page callback' => 'tool_overview',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => -8,
  );
  $items['tool/blast'] = array (
      'title' => 'BLAST',
      'access arguments' => TRUE,
      'page callback' => 'blast_toolpage',
      'type' => MENU_LOCAL_TASK,
      'weight' => 0,
  );
  $items['tool/clustal'] = array (
      'title' => 'Clustal',
      'access arguments' => TRUE,
      'page callback' => 'clustal_toolpage',
      'type' => MENU_LOCAL_TASK,
      'weight' => 1,
  );
  $items['tool/cap'] = array (
      'title' => 'Community Annotation',
      'access arguments' => TRUE,
      'page callback' => 'cap_toolpage',
      'type' => MENU_LOCAL_TASK,
      'weight' => 2,
  );
  return $items;
}

function tool_overview() {
  $output = t('The following tools are available...');
  return $output;
}

function blast_toolpage() {
  return t('BLAST CODE HERE');
}

function clustal_toolpage() {
  return t('Clustal stuff here');
}

function cap_toolpage() {
  return t('CAP code here');
}
